name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    env:
      SKIP_YARN_COREPACK_CHECK: '1'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint files
        run: yarn lint

      - name: Typecheck files
        run: yarn typecheck

  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          skip-dirs: node_modules
          exit-code: 1

  release:
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci') && github.repository_owner == 'gr4vy' && github.ref == 'refs/heads/main'"
    runs-on: ubuntu-latest
    env:
      SKIP_YARN_COREPACK_CHECK: '1'

    needs:
      - lint
      - scan

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.DISPATCH_ACCESS_TOKEN }}

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Setup
        uses: ./.github/actions/setup

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.DISPATCH_ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn prepack
          yarn release
